:numbered!:

== Comments and Feedback

In the spirit of open source, we invite anyone to provide feedback and comments on any reference architecture. Although we review our papers internally, sometimes issues or typographical errors are encountered. Feedback allows us to not only improve the quality of the papers we produce, but allows the reader to provide their thoughts on potential improvements and topic expansion to the papers.
Feedback on the papers can be provided by emailing refarch-feedback@redhat.com. Please refer to the title within the email.

=== _Staying In Touch_

Join us on some of the popular social media sites where we keep our audience informed on new reference architectures as well as offer related information on things we find interesting.

==== _Like us on Facebook_
https://www.facebook.com/rhrefarch

==== _Follow us on Twitter_
https://twitter.com/RedHatRefArch

==== _Plus us on Google+_
https://plus.google.com/u/0/b/114152126783830728030/

// vim: set syntax=asciidoc:
// vim: set syntax=asciidoc:
